name: peshat
description: Point your camera at any text, get an instant translation.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.0
  flutter_doc_scanner: ^0.0.21
  google_mlkit_text_recognition: ^0.13.0
  google_mlkit_translation: ^0.11.1
  google_mlkit_language_id: ^0.11.0
  google_mobile_ads: ^6.0.0
  in_app_purchase: ^3.2.0
  shared_preferences: ^2.3.0
  package_info_plus: ^8.1.0
  share_plus: ^10.1.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  google_fonts: 6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3
flutter:
  generate: true
  assets:
    - assets/icon/
    - assets/splash/

flutter_native_splash:
  color: "#EDEAE2"
  image: assets/splash/logo.png
  color_dark: "#14171C"
  image_dark: assets/splash/logo.png
  android_12:
    color: "#EDEAE2"
    image: assets/splash/logo.png
    icon_background_color: "#EDEAE2"
    color_dark: "#14171C"
    image_dark: assets/splash/logo.png
    icon_background_color_dark: "#14171C"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#EDEAE2"
  adaptive_icon_foreground: "assets/icon/icon.png"
  remove_alpha_ios: true
